export const SERVICES = {
  github: {
    name: 'github',
    displayName: 'GitHub',
    description: 'GitHub is a code hosting platform for version control and collaboration using Git.',
    auth: { type: 'bearer', header: 'Authorization', envVar: 'GITHUB_TOKEN', format: 'token {value}', docsUrl: 'https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens' },
    baseUrl: 'https://api.github.com',
    docsUrl: 'https://docs.github.com/en/rest',
    capabilities: [
      'Create, read, update, and delete repositories',
      'Manage issues: create, label, assign, close, comment',
      'Pull requests: create, review, merge, request changes',
      'Releases and tags: create releases, upload assets',
      'GitHub Actions: trigger workflows, view run logs',
      'Repository search: code, issues, users, commits',
      'Gists: create and manage code snippets',
      'Organization and team management',
      'Webhooks: register and manage event subscriptions',
      'Code review: inline comments, review approvals',
      'Branch protection rules and repo settings',
      'GitHub Discussions management',
    ],
    useCases: ['Automate issue triage and labeling', 'Generate release notes from merged PRs', 'Monitor CI/CD pipeline status', 'Batch-update stale issues'],
  },

  notion: {
    name: 'notion',
    displayName: 'Notion',
    description: 'Notion is an all-in-one workspace for notes, docs, databases, and project management.',
    auth: { type: 'bearer', header: 'Authorization', envVar: 'NOTION_TOKEN', format: 'Bearer {value}', docsUrl: 'https://developers.notion.com/docs/authorization' },
    baseUrl: 'https://api.notion.com/v1',
    docsUrl: 'https://developers.notion.com',
    capabilities: [
      'Create, read, update, and archive pages',
      'Query and filter database entries with complex filters',
      'Create and update database properties and schema',
      'Append, read, and delete blocks (paragraphs, todos, code, etc.)',
      'Search across all accessible pages and databases',
      'Retrieve and update page properties',
      'Manage comments on pages and discussions',
      'List workspace users and retrieve user info',
      'Create child pages and database entries',
      'Full Markdown-to-blocks conversion support',
    ],
    useCases: ['Sync tasks from external tools into a Notion database', 'Append daily standup notes to a shared page', 'Query project database to generate status reports'],
  },

  slack: {
    name: 'slack',
    displayName: 'Slack',
    description: 'Slack is a business communication platform offering messaging, file sharing, and integrations.',
    auth: { type: 'bearer', header: 'Authorization', envVar: 'SLACK_BOT_TOKEN', format: 'Bearer {value}', docsUrl: 'https://api.slack.com/authentication/oauth-v2' },
    baseUrl: 'https://slack.com/api',
    docsUrl: 'https://api.slack.com/methods',
    capabilities: [
      'Post messages to channels, DMs, and threads',
      'Update and delete existing messages',
      'React to messages with emoji reactions',
      'Upload and share files and snippets',
      'List, join, and leave channels',
      'Search messages across the workspace',
      'Retrieve user and workspace information',
      'Create and manage scheduled messages',
      'Open interactive modals and respond to shortcuts',
      'Set channel topics and purposes',
      'Pin and unpin messages',
    ],
    useCases: ['Post deployment notifications to #releases', 'Alert on-call engineers when monitors fail', 'Send daily digest summaries to a channel'],
  },

  linear: {
    name: 'linear',
    displayName: 'Linear',
    description: 'Linear is a project management tool for software teams with a focus on speed and simplicity.',
    auth: { type: 'bearer', header: 'Authorization', envVar: 'LINEAR_API_KEY', format: 'Bearer {value}', docsUrl: 'https://developers.linear.app/docs/graphql/working-with-the-graphql-api' },
    baseUrl: 'https://api.linear.app/graphql',
    docsUrl: 'https://developers.linear.app',
    capabilities: [
      'Create, update, and archive issues',
      'Assign issues to team members and set priorities',
      'Manage labels, states, and estimates',
      'Query issues with powerful filtering (team, label, assignee, status)',
      'Create and manage projects and milestones',
      'Work with cycles (sprints) and roadmaps',
      'Retrieve team structure and member information',
      'Subscribe to webhooks for issue state changes',
      'Create comments and reactions on issues',
      'Move issues between teams and manage sub-issues',
    ],
    useCases: ['Triage GitHub issues into Linear', 'Generate sprint summary reports', 'Bulk-update issue priorities based on customer feedback'],
  },

  stripe: {
    name: 'stripe',
    displayName: 'Stripe',
    description: 'Stripe is a payments infrastructure platform for accepting online and in-person payments.',
    auth: { type: 'bearer', header: 'Authorization', envVar: 'STRIPE_SECRET_KEY', format: 'Bearer {value}', docsUrl: 'https://stripe.com/docs/api/authentication' },
    baseUrl: 'https://api.stripe.com/v1',
    docsUrl: 'https://stripe.com/docs/api',
    capabilities: [
      'Create and manage payment intents and charges',
      'Customer lifecycle: create, retrieve, update, delete',
      'Subscriptions: create, update, cancel, pause',
      'Products and prices: catalog management',
      'Invoices: create, finalize, void, and send',
      'Refunds: issue full or partial refunds',
      'Webhooks: listen and handle Stripe events',
      'Connect: manage connected accounts and transfers',
      'Checkout sessions for hosted payment pages',
      'Balance and payout management',
      'Dispute and fraud review management',
    ],
    useCases: ['Provision access after successful payment', 'Send payment failure alerts', 'Generate monthly revenue summaries', 'Sync subscription status to a database'],
  },

  jira: {
    name: 'jira',
    displayName: 'Jira',
    description: 'Jira is an issue and project tracking tool from Atlassian, widely used by engineering and ops teams.',
    auth: { type: 'basic', envVar: 'JIRA_EMAIL / JIRA_API_TOKEN', docsUrl: 'https://developer.atlassian.com/cloud/jira/platform/basic-auth-for-rest-apis/' },
    baseUrl: 'https://{domain}.atlassian.net/rest/api/3',
    docsUrl: 'https://developer.atlassian.com/cloud/jira/platform/rest/v3',
    capabilities: [
      'Create, read, update, and delete issues',
      'Transition issues through workflow states',
      'Assign issues and manage reporters',
      'Add and retrieve comments and attachments',
      'Search issues with JQL (Jira Query Language)',
      'Manage sprints: start, complete, and move issues',
      'Board management: retrieve sprint and backlog items',
      'Component and version management',
      'Bulk issue operations',
      'Custom field reading and writing',
      'Project configuration and metadata retrieval',
    ],
    useCases: ['Sync bug reports from production into a Jira board', 'Generate sprint velocity reports', 'Triage and assign incoming support tickets'],
  },

  gmail: {
    name: 'gmail',
    displayName: 'Gmail',
    description: 'Gmail is Google\'s email service, accessible via the Gmail REST API for reading, sending, and organizing email.',
    auth: { type: 'oauth2', envVar: 'GOOGLE_ACCESS_TOKEN', docsUrl: 'https://developers.google.com/gmail/api/auth/about-auth' },
    baseUrl: 'https://gmail.googleapis.com/gmail/v1',
    docsUrl: 'https://developers.google.com/gmail/api/reference/rest',
    capabilities: [
      'Send emails with HTML or plain text body',
      'Read and retrieve messages and threads',
      'Search messages with Gmail query syntax',
      'List, create, update, and delete labels',
      'Apply and remove labels from messages',
      'Draft management: create, update, send, delete',
      'Thread management: reply-all, forward, archive',
      'Mark messages as read/unread, star/unstar',
      'History: retrieve recent changes since a historyId',
      'Batch modify: apply changes to multiple messages',
      'Filters and forwarding settings management',
    ],
    useCases: ['Parse order confirmation emails and extract data', 'Send automated follow-up emails', 'Label and archive newsletters automatically'],
  },

  asana: {
    name: 'asana',
    displayName: 'Asana',
    description: 'Asana is a work management platform for organizing tasks, projects, and team workflows.',
    auth: { type: 'bearer', header: 'Authorization', envVar: 'ASANA_PAT', format: 'Bearer {value}', docsUrl: 'https://developers.asana.com/docs/authentication-basics' },
    baseUrl: 'https://app.asana.com/api/1.0',
    docsUrl: 'https://developers.asana.com/reference/rest-api-reference',
    capabilities: [
      'Create, read, update, and delete tasks',
      'Assign tasks, set due dates, and add followers',
      'Create and manage projects and sections',
      'Add subtasks and task dependencies',
      'Manage tags and custom fields on tasks',
      'Portfolio and goal management',
      'Team and workspace membership queries',
      'Attachments: upload files and external links',
      'Search across tasks, projects, and users',
      'Webhooks for task and project event notifications',
      'Reporting: status updates and project progress',
    ],
    useCases: ['Create tasks from Slack messages or GitHub issues', 'Generate weekly project status summaries', 'Sync calendar events to Asana tasks'],
  },

  vercel: {
    name: 'vercel',
    displayName: 'Vercel',
    description: 'Vercel is a cloud platform for deploying and hosting frontend apps and serverless functions.',
    auth: { type: 'bearer', header: 'Authorization', envVar: 'VERCEL_TOKEN', format: 'Bearer {value}', docsUrl: 'https://vercel.com/docs/rest-api#authentication' },
    baseUrl: 'https://api.vercel.com',
    docsUrl: 'https://vercel.com/docs/rest-api',
    capabilities: [
      'List and inspect deployments with status and logs',
      'Create deployments and trigger redeploys',
      'Promote deployments to production',
      'List, create, and delete projects',
      'Environment variable management (read, write, delete)',
      'Domain and DNS record management',
      'Edge Config: read and write edge config stores',
      'Function log streaming and error inspection',
      'Team member and permission management',
      'Webhook registration for deployment events',
      'Analytics and performance metrics retrieval',
    ],
    useCases: ['Trigger redeploys after content changes', 'Monitor failed deployments and alert on-call', 'Sync environment variables across environments'],
  },

  figma: {
    name: 'figma',
    displayName: 'Figma',
    description: 'Figma is a collaborative design tool for UI/UX design, prototyping, and design systems.',
    auth: { type: 'bearer', header: 'X-Figma-Token', envVar: 'FIGMA_PAT', docsUrl: 'https://www.figma.com/developers/api#auth' },
    baseUrl: 'https://api.figma.com/v1',
    docsUrl: 'https://www.figma.com/developers/api',
    capabilities: [
      'Read file structure: pages, frames, components, groups',
      'Export frames and components as PNG, SVG, or PDF',
      'Retrieve component and component set metadata',
      'Access shared styles (colors, typography, effects)',
      'Read and write variables and variable collections',
      'List and retrieve file versions and change history',
      'Post and reply to comments on frames',
      'Webhook subscriptions for file change events',
      'Team library: list published components and styles',
      'User and team membership information',
    ],
    useCases: ['Export design tokens to code', 'Generate asset manifests for design handoff', 'Sync color palettes and typography to a style dictionary'],
  },
};

export function getService(name) {
  const svc = SERVICES[name?.toLowerCase()];
  if (!svc) {
    const valid = Object.keys(SERVICES).join(', ');
    throw new Error(`Unknown service "${name}". Valid services: ${valid}`);
  }
  return svc;
}
