export const TOOLS = {
  ffuf: {
    name: 'ffuf',
    displayName: 'ffuf',
    description: 'ffuf (Fuzz Faster U Fool) is a fast web fuzzer written in Go, used for directory/file discovery, parameter fuzzing, and virtual host enumeration.',
    docsUrl: 'https://github.com/ffuf/ffuf',
    commonFlags: [
      '-u <url>          Target URL with FUZZ keyword as placeholder',
      '-w <wordlist>     Wordlist file path (use - for stdin)',
      '-H <header>       Custom header (repeatable: -H "Cookie: x=1")',
      '-mc <codes>       Match HTTP status codes (default: 200,204,301,302,307,401,403)',
      '-fc <codes>       Filter HTTP status codes',
      '-ms <size>        Match response size',
      '-fs <size>        Filter response size',
      '-fw <words>       Filter by word count',
      '-fl <lines>       Filter by line count',
      '-t <threads>      Concurrent threads (default: 40)',
      '-o <file>         Output file path',
      '-of <format>      Output format: json, ejson, html, md, csv, ecsv',
      '-c                Colorize output',
      '-v                Verbose output',
      '-r                Follow redirects',
      '-p <delay>        Delay between requests (e.g. 0.1 or 0.1-2.0)',
      '-recursion        Enable recursive fuzzing',
      '-d <body>         POST data with FUZZ keyword',
      '-X <method>       HTTP method (default: GET)',
      '-b <cookies>      Cookie header value',
    ],
    capabilities: [
      'Directory and file discovery via wordlist fuzzing',
      'Virtual host (vhost) enumeration by fuzzing Host header',
      'Parameter name and value fuzzing for API endpoints',
      'Subdomain discovery using DNS-based fuzzing',
      'POST body fuzzing for form inputs and JSON APIs',
      'Multi-position fuzzing using multiple FUZZ keywords (W1, W2...)',
      'Response filtering by status code, size, word count, or line count',
      'Output results in JSON, CSV, HTML, or Markdown formats',
      'Recursive directory fuzzing with depth control',
      'Request rate limiting to avoid detection/blocking',
      'Cluster bomb and pitchfork attack modes for multi-parameter fuzzing',
    ],
    useCases: ['Find hidden admin panels', 'Enumerate API endpoints', 'Discover backup files with common extensions', 'Fuzz parameter values for injection testing'],
  },

  nmap: {
    name: 'nmap',
    displayName: 'Nmap',
    description: 'Nmap (Network Mapper) is an open-source tool for network discovery, port scanning, service detection, and security auditing.',
    docsUrl: 'https://nmap.org/book/man.html',
    commonFlags: [
      '-p <ports>        Port ranges (e.g. 80,443 or 1-1000 or -p-)',
      '-sV               Service version detection',
      '-sS               SYN (stealth) scan (requires root)',
      '-sU               UDP scan',
      '-sC               Run default NSE scripts',
      '-A                Aggressive scan: OS, version, scripts, traceroute',
      '-O                OS detection (requires root)',
      '-oA <basename>    Output in all formats (normal, XML, grepable)',
      '-oN <file>        Normal output to file',
      '-oX <file>        XML output to file',
      '-oG <file>        Grepable output to file',
      '-T<0-5>           Timing template (0=paranoid, 3=normal, 5=insane)',
      '--script <name>   Run specific NSE scripts',
      '--open            Only show open ports',
      '-v                Verbose output',
      '-n                No DNS resolution',
      '--min-rate <n>    Minimum packet rate',
      '-iL <file>        Input from host list file',
      '--exclude <hosts> Exclude hosts from scan',
    ],
    capabilities: [
      'TCP and UDP port scanning across single hosts or entire subnets',
      'Service and version detection for running processes',
      'Operating system fingerprinting using TCP/IP stack analysis',
      'NSE (Nmap Scripting Engine) for vulnerability detection',
      'Host discovery: ping, ARP, DNS, and SYN probes',
      'Firewall and IDS evasion techniques (fragmentation, decoys)',
      'Traceroute and network topology mapping',
      'Output in XML, JSON-compatible, grepable, and normal formats',
      'Parallel scanning with configurable timing and rate control',
      'SMB, HTTP, SSL/TLS, and SSH service interrogation scripts',
      'Vulnerability scanning with vuln script category',
    ],
    useCases: ['Enumerate open ports on a target during recon', 'Detect service versions for CVE matching', 'Identify live hosts on a subnet', 'Run vuln scripts for quick assessment'],
  },

  gobuster: {
    name: 'gobuster',
    displayName: 'Gobuster',
    description: 'Gobuster is a tool for brute-forcing URIs, DNS subdomains, virtual host names, S3/GCS buckets, and TFTP servers.',
    docsUrl: 'https://github.com/OJ/gobuster',
    commonFlags: [
      'dir                Directory/file brute-force mode',
      'dns                DNS subdomain brute-force mode',
      'vhost              Virtual host brute-force mode',
      '-u <url>           Target URL (dir/vhost mode)',
      '-d <domain>        Target domain (dns mode)',
      '-w <wordlist>      Path to wordlist',
      '-t <threads>       Concurrent threads (default: 10)',
      '-x <extensions>    File extensions to append (e.g. php,html,txt)',
      '-o <file>          Output file path',
      '-s <codes>         Positive status codes (default: 200,204,301,302,307,401,403)',
      '-b <codes>         Negative status codes to blacklist',
      '-l                 Include length of response body',
      '-q                 Quiet mode',
      '-r                 Follow redirects',
      '-k                 Skip TLS certificate verification',
      '-H <header>        Custom headers',
      '-c <cookie>        Cookie to use for requests',
      '--no-error         Suppress error messages',
      '-z                 Show progress',
    ],
    capabilities: [
      'Directory and file brute-forcing with wordlists and extension appending',
      'DNS subdomain enumeration with wildcard detection',
      'Virtual host discovery by brute-forcing Host header',
      'AWS S3 and GCS bucket enumeration',
      'Configurable status code filtering (whitelist and blacklist)',
      'Multi-threaded scanning with progress reporting',
      'Custom header injection for authenticated scanning',
      'Output to file in plaintext format',
      'TLS/SSL certificate verification bypass',
      'Redirect following with depth control',
    ],
    useCases: ['Brute-force directories on a web server', 'Enumerate subdomains of a domain', 'Find virtual hosts behind an IP', 'Discover PHP/ASP/HTML files in a directory'],
  },

  sqlmap: {
    name: 'sqlmap',
    displayName: 'sqlmap',
    description: 'sqlmap is an open-source penetration testing tool that automates the detection and exploitation of SQL injection vulnerabilities.',
    docsUrl: 'https://sqlmap.org',
    commonFlags: [
      '-u <url>           Target URL',
      '-p <param>         Testable parameter',
      '--data <data>      POST data string',
      '--cookie <cookie>  HTTP Cookie header value',
      '--headers <hdrs>   Extra headers (newline-separated)',
      '--dbs              Enumerate databases',
      '--tables           Enumerate tables (-D for specific DB)',
      '--columns          Enumerate columns (-T for specific table)',
      '--dump             Dump table contents',
      '--dump-all         Dump all databases',
      '-D <db>            DBMS database to enumerate',
      '-T <table>         DBMS table to enumerate',
      '-C <columns>       Comma-delimited column list',
      '--level <1-5>      Level of tests to perform (default: 1)',
      '--risk <1-3>       Risk of tests to perform (default: 1)',
      '--batch            Never ask for user input, use defaults',
      '--random-agent     Use random HTTP User-Agent',
      '--technique <tech> SQL injection techniques (BEUSTQ)',
      '--dbms <dbms>      Force backend DBMS',
      '--os-shell         Prompt for OS shell (requires stacked queries)',
    ],
    capabilities: [
      'Automatic detection of SQL injection flaws (boolean, time-based, error, union, stacked)',
      'Database fingerprinting (MySQL, PostgreSQL, MSSQL, Oracle, SQLite, etc.)',
      'Enumeration of databases, tables, columns, and row data',
      'Data extraction via UNION-based, error-based, and blind techniques',
      'File system access: read and write files on the server',
      'Operating system command execution via xp_cmdshell or stacked queries',
      'Privilege escalation checks and user account enumeration',
      'Tamper scripts for WAF/IDS evasion',
      'Session token and cookie injection',
      'Bulk scanning using -m flag for multiple targets',
    ],
    useCases: ['Test a login form for SQLi vulnerabilities', 'Dump the users table from a vulnerable app', 'Check for blind SQLi in a search endpoint', 'Enumerate all databases on a target'],
  },

  burpsuite: {
    name: 'burpsuite',
    displayName: 'Burp Suite',
    description: 'Burp Suite is a web application security testing platform with proxy, scanner, intruder, repeater, and collaborator tools. The REST API enables automation.',
    docsUrl: 'https://portswigger.net/burp/documentation/desktop/tools',
    commonFlags: [
      'Proxy        Intercept and modify HTTP/S traffic',
      'Scanner      Automated vulnerability scanning (Pro/Enterprise)',
      'Intruder     Automated parameter fuzzing with payload lists',
      'Repeater     Manual request replay and modification',
      'Sequencer    Token entropy analysis',
      'Decoder      Encode/decode data (Base64, URL, HTML, etc.)',
      'Comparer     Diff two requests or responses',
      'Collaborator Out-of-band vulnerability testing (SSRF, blind XSS)',
      'REST API     /scan, /issues, /target, /proxy endpoints (localhost:1337)',
    ],
    capabilities: [
      'HTTP/S proxy with full request/response interception and modification',
      'Automated web vulnerability scanning for OWASP Top 10',
      'Intruder: cluster bomb, sniper, pitchfork, and battering ram attack modes',
      'Repeater: replay and modify individual requests with diffing',
      'Out-of-band (OAST) detection via Burp Collaborator',
      'REST API for scripted scan initiation, status polling, and issue retrieval',
      'Target scope management and site map generation',
      'Active and passive scanning with configurable issue categories',
      'Session handling rules for cookie and token management',
      'Extension support via BApp Store and custom Java/Python extensions',
    ],
    useCases: ['Intercept and replay authenticated API requests', 'Automate scans via REST API in CI/CD', 'Fuzz form inputs with custom payload lists', 'Test OAuth flows with Repeater'],
  },

  gh: {
    name: 'gh',
    displayName: 'GitHub CLI (gh)',
    description: 'The GitHub CLI (gh) brings GitHub to the terminal: PRs, issues, repos, gists, actions, and the GitHub API — all from the command line.',
    docsUrl: 'https://cli.github.com/manual',
    commonFlags: [
      'gh pr create       Create a pull request',
      'gh pr list         List pull requests',
      'gh pr view <num>   View a pull request',
      'gh pr merge <num>  Merge a pull request',
      'gh pr checkout     Check out a PR branch locally',
      'gh issue create    Create an issue',
      'gh issue list      List issues with filters',
      'gh issue close     Close an issue',
      'gh issue comment   Add a comment to an issue',
      'gh repo clone      Clone a repository',
      'gh repo create     Create a new repository',
      'gh repo fork       Fork a repository',
      'gh run list        List workflow runs',
      'gh run view        View a workflow run',
      'gh run watch       Watch a workflow run in real time',
      'gh api <endpoint>  Make a raw API call',
      'gh auth login      Authenticate with GitHub',
      'gh gist create     Create a gist',
      'gh release create  Create a release',
    ],
    capabilities: [
      'Full pull request lifecycle: create, view, review, merge, close',
      'Issue management: create, label, assign, close, comment',
      'Repository operations: clone, fork, create, view, delete',
      'GitHub Actions: list runs, view logs, re-run jobs, download artifacts',
      'Release management: create, upload assets, delete',
      'Direct REST and GraphQL API access via gh api',
      'Gist creation and management',
      'Authentication and credential management',
      'Environment and secret management for repos and orgs',
      'Code search, topic, and label management',
    ],
    useCases: ['Create PRs from a feature branch in CI', 'Bulk-close stale issues via scripting', 'Trigger and monitor GitHub Actions workflows', 'Manage repo secrets from the terminal'],
  },

  vercel: {
    name: 'vercel',
    displayName: 'Vercel CLI',
    description: 'The Vercel CLI deploys and manages projects on Vercel: deployments, env vars, domains, logs, and local dev.',
    docsUrl: 'https://vercel.com/docs/cli',
    commonFlags: [
      'vercel            Deploy current directory (preview)',
      'vercel --prod     Deploy to production',
      'vercel dev        Start local dev server with edge functions',
      'vercel env ls     List env variables',
      'vercel env add    Add an env variable interactively',
      'vercel env rm     Remove an env variable',
      'vercel env pull   Pull env vars to local .env file',
      'vercel domains ls List domains for a project',
      'vercel domains add Add a domain',
      'vercel logs       Stream deployment logs',
      'vercel inspect    Inspect a deployment',
      'vercel link       Link local directory to a Vercel project',
      'vercel list       List deployments',
      'vercel promote    Promote a deployment to production',
      'vercel rollback   Roll back to a previous deployment',
      'vercel pull       Pull project settings from Vercel',
      'vercel build      Build locally using Vercel build pipeline',
      '--token <token>   Pass Vercel token for CI environments',
    ],
    capabilities: [
      'Deploy projects to preview and production environments',
      'Local development server with Vercel edge function simulation',
      'Environment variable management across development, preview, production',
      'Domain registration, assignment, and DNS management',
      'Real-time log streaming for deployments and functions',
      'Deployment inspection: URL, build logs, function details',
      'Production promotion and rollback',
      'Project linking and configuration management',
      'Build cache management and forced rebuilds',
      'Team and project switching via --scope flag',
    ],
    useCases: ['Deploy a Next.js app to production', 'Sync env vars to local .env for dev', 'Inspect a failed deployment for errors', 'Promote a preview to production after QA'],
  },

  stripe: {
    name: 'stripe',
    displayName: 'Stripe CLI',
    description: 'The Stripe CLI lets you build, test, and debug Stripe integrations locally: webhook forwarding, API calls, event triggering, and fixture loading.',
    docsUrl: 'https://stripe.com/docs/stripe-cli',
    commonFlags: [
      'stripe listen          Forward webhooks to localhost',
      'stripe trigger <event> Trigger a test webhook event',
      'stripe login           Authenticate with your Stripe account',
      'stripe logs tail       Tail Stripe API request logs',
      'stripe customers list  List customers',
      'stripe customers retrieve <id>  Retrieve a customer',
      'stripe payment-intents create   Create a payment intent',
      'stripe subscriptions list       List subscriptions',
      'stripe fixtures run <file>      Run a fixtures file',
      'stripe open dashboard           Open the Stripe dashboard',
      '--api-key <key>        Use a specific API key',
      '--stripe-account <id>  Operate on a connected account',
      '--limit <n>            Limit number of results',
      '-d <param>             Additional API parameter (flag-style)',
    ],
    capabilities: [
      'Local webhook forwarding with automatic HTTPS tunnel',
      'Test event triggering for all Stripe event types',
      'API request log tailing in real time',
      'Direct resource management: customers, payment intents, subscriptions',
      'Fixture files for reproducible test data setup and teardown',
      'Multi-account support with --stripe-account flag',
      'Restricted key generation for sandboxed access',
      'Resend recent webhook events for retry testing',
      'Product, price, and coupon management from the terminal',
      'Connected account operations via Stripe Connect',
    ],
    useCases: ['Forward webhooks to local server during development', 'Trigger payment.succeeded to test fulfillment logic', 'Load fixture data for automated test suites', 'Tail API logs when debugging webhook failures'],
  },

  httpx: {
    name: 'httpx',
    displayName: 'httpx',
    description: 'httpx is a fast and multi-purpose HTTP toolkit from ProjectDiscovery for probing web servers, analyzing responses, and running HTTP-based recon.',
    docsUrl: 'https://github.com/projectdiscovery/httpx',
    commonFlags: [
      '-u <url>              Single target URL',
      '-l <file>             Input file with list of URLs/hosts',
      '-sc                   Show status codes',
      '-cl                   Show content length',
      '-ct                   Show content type',
      '-title                Show page title',
      '-server               Show server header',
      '-tech-detect          Run technology detection (Wappalyzer)',
      '-follow-redirects     Follow HTTP redirects',
      '-random-agent         Use a random User-Agent',
      '-H <header>           Custom header',
      '-mc <codes>           Match status codes',
      '-fc <codes>           Filter status codes',
      '-timeout <seconds>    Per-request timeout',
      '-threads <n>          Concurrent threads',
      '-o <file>             Output file',
      '-json                 JSON output',
      '-silent               Suppress banner',
      '-probe                Show probe status',
    ],
    capabilities: [
      'Probe large lists of hosts/URLs for liveness and status codes',
      'Extract titles, server headers, content types, and content length',
      'Technology detection using Wappalyzer signatures',
      'Follow redirect chains and report final destination',
      'Filter and match responses by status code, size, or keyword',
      'JSON output for pipeline integration with other tools',
      'TLS certificate inspection and fingerprinting',
      'Screenshot capture of live web pages',
      'Port scanning combined with HTTP probing',
      'Response body extraction and pattern matching',
    ],
    useCases: ['Probe a subdomain list for live hosts before further enumeration', 'Identify web technologies across a large target scope', 'Filter URLs by status code for focused testing'],
  },

  nuclei: {
    name: 'nuclei',
    displayName: 'nuclei',
    description: 'Nuclei is a fast, template-based vulnerability scanner from ProjectDiscovery that runs community-maintained YAML templates against targets.',
    docsUrl: 'https://docs.projectdiscovery.io/tools/nuclei',
    commonFlags: [
      '-u <url>              Single target URL',
      '-l <file>             File with list of targets',
      '-t <template>         Specific template or directory',
      '-tags <tag>           Run templates with matching tags (e.g. cve,xss)',
      '-severity <level>     Filter by severity: info,low,medium,high,critical',
      '-etags <tag>          Exclude templates with these tags',
      '-es <severity>        Exclude templates by severity',
      '-rl <n>               Global rate limit (requests/second)',
      '-c <n>                Concurrency (templates in parallel)',
      '-o <file>             Output results to file',
      '-json                 JSON output format',
      '-silent               Show only results',
      '-update-templates     Update nuclei templates to latest',
      '-exclude-templates    Comma-separated template paths to exclude',
      '-stats                Show real-time scan statistics',
      '-resume               Resume scan from last saved state',
      '-H <header>           Custom header',
      '-proxy <url>          HTTP proxy',
    ],
    capabilities: [
      'Run thousands of community templates for known CVEs and misconfigurations',
      'Filter scans by severity, tag, protocol, or template ID',
      'Support for HTTP, DNS, TCP, SSL, file, and headless browser templates',
      'Workflow templates for chained, conditional scanning',
      'Rate limiting and concurrency control to avoid detection',
      'JSON output for integration with SIEM and ticketing systems',
      'Custom template authoring in YAML with matcher logic',
      'Subdomain takeover, exposed panel, and default credential checks',
      'API fuzzing templates for parameter injection and auth bypass',
      'CI/CD integration for automated vulnerability scanning in pipelines',
    ],
    useCases: ['Run CVE templates against a target web app', 'Scan for exposed admin panels and default credentials', 'Add automated security scanning to a CI/CD pipeline'],
  },

  curl: {
    name: 'curl',
    displayName: 'curl',
    description: 'curl is a command-line tool for transferring data with URLs, supporting HTTP, HTTPS, FTP, and dozens of other protocols.',
    docsUrl: 'https://curl.se/docs/manpage.html',
    commonFlags: [
      '-X <method>           HTTP method (GET, POST, PUT, DELETE, PATCH)',
      '-H <header>           Request header (repeatable)',
      '-d <data>             Request body data',
      '--data-raw <data>     Raw request body (no URL encoding)',
      '-u <user:pass>        Basic auth credentials',
      '-b <cookies>          Send cookies',
      '-c <file>             Save cookies to file',
      '-L                    Follow redirects',
      '-I                    Fetch headers only (HEAD request)',
      '-s                    Silent mode (suppress progress)',
      '-o <file>             Write output to file',
      '-O                    Save with remote filename',
      '-v                    Verbose (show headers and SSL info)',
      '-k                    Skip TLS certificate verification',
      '--compressed          Request compressed response',
      '-F <field=value>      Multipart form data upload',
      '--json <data>         Send JSON body with correct Content-Type',
      '--retry <n>           Retry on transient failure',
    ],
    capabilities: [
      'Make HTTP requests with any method, headers, and body',
      'Authenticate with Basic, Bearer token, OAuth, and certificate auth',
      'Upload and download files including multipart form data',
      'Follow redirects and handle cookies across requests',
      'Inspect TLS certificate details and bypass verification in testing',
      'Pipe responses into other tools or save to disk',
      'Debug API requests with verbose header and timing output',
      'Test REST APIs without a browser or GUI client',
      'Batch requests via scripting with shell loops',
      'Support for proxy routing and custom DNS resolution',
    ],
    useCases: ['Quickly test an API endpoint with a custom Bearer token', 'Download a remote file to a server via SSH session', 'Debug an authentication flow by inspecting raw request/response headers'],
  },

  jq: {
    name: 'jq',
    displayName: 'jq',
    description: 'jq is a lightweight and flexible command-line JSON processor for slicing, filtering, mapping, and transforming JSON data.',
    docsUrl: 'https://jqlang.org/manual/',
    commonFlags: [
      '.<key>                Select a field by key',
      '.[]                   Iterate over array elements or object values',
      '.key1, .key2          Select multiple fields',
      'select(expr)          Filter elements matching a condition',
      'map(expr)             Transform each element in an array',
      'length                Get length of array, string, or object',
      'keys                  Get sorted array of object keys',
      'values                Get array of object values',
      'to_entries             Convert object to [{key, value}] array',
      'from_entries           Convert [{key, value}] array back to object',
      'with_entries           Map over key-value pairs',
      'has(<key>)            Test if object has a key',
      'type                  Return the type of a value',
      'sort_by(.field)       Sort array of objects by field',
      'group_by(.field)      Group array by field value',
      'unique_by(.field)     Deduplicate by field',
      '-r                    Raw string output (no JSON quoting)',
      '-c                    Compact output (no pretty printing)',
    ],
    capabilities: [
      'Extract and transform nested JSON fields with path expressions',
      'Filter arrays and objects with conditional select expressions',
      'Map, reduce, and reshape JSON data structures',
      'Sort, group, and deduplicate arrays of objects',
      'Combine and merge multiple JSON documents',
      'Format, pretty-print, and compact JSON output',
      'Generate CSV or TSV from JSON with @csv and @tsv',
      'Use as a pipeline stage to process API responses in shell scripts',
      'Construct new JSON documents from existing data',
      'Debug and explore unknown JSON schemas interactively',
    ],
    useCases: ['Parse API responses in a shell pipeline', 'Extract specific fields from a large JSON config file', 'Transform and reshape data between systems that use different JSON schemas'],
  },

  docker: {
    name: 'docker',
    displayName: 'Docker',
    description: 'Docker is a platform for building, running, and managing containerized applications with images and containers.',
    docsUrl: 'https://docs.docker.com/reference/cli/docker/',
    commonFlags: [
      'build -t <name> .     Build an image from a Dockerfile',
      'run -d -p <h:c>       Run container detached with port mapping',
      'run --rm              Remove container after it exits',
      '-e <KEY=VAL>          Set environment variable',
      '-v <host:container>   Bind mount a volume',
      '--name <name>         Assign a name to the container',
      'ps -a                 List all containers (including stopped)',
      'logs -f <container>   Tail container logs',
      'exec -it <c> bash     Open interactive shell in running container',
      'stop / kill           Stop or force-kill a container',
      'rm / rmi              Remove a container or image',
      'pull <image>          Pull image from registry',
      'push <image>          Push image to registry',
      'inspect <container>   Show low-level container/image info',
      'network ls            List Docker networks',
      'volume ls             List Docker volumes',
      'compose up -d         Start services defined in docker-compose.yml',
      'system prune          Remove unused containers, images, and networks',
    ],
    capabilities: [
      'Build Docker images from Dockerfiles with layer caching',
      'Run containers with port mapping, environment variables, and volumes',
      'Manage container lifecycle: start, stop, restart, remove',
      'Tail and inspect container logs for debugging',
      'Execute commands inside running containers interactively',
      'Manage Docker networks for container-to-container communication',
      'Use Docker Compose to orchestrate multi-container applications',
      'Push and pull images from Docker Hub or private registries',
      'Inspect image layers, container metadata, and resource usage',
      'Prune unused resources to free disk space',
    ],
    useCases: ['Build and run a containerized app locally before deploying', 'Debug a failing container by tailing logs and exec-ing in', 'Manage a multi-service local dev environment with Docker Compose'],
  },

  kubectl: {
    name: 'kubectl',
    displayName: 'kubectl',
    description: 'kubectl is the Kubernetes command-line tool for deploying applications, inspecting cluster resources, and managing workloads.',
    docsUrl: 'https://kubernetes.io/docs/reference/kubectl/',
    commonFlags: [
      'get <resource>        List resources (pods, deployments, services...)',
      'describe <r> <name>   Show detailed info about a resource',
      'apply -f <file>       Apply a manifest file or directory',
      'delete -f <file>      Delete resources from a manifest',
      'logs <pod>            Print container logs',
      'logs -f               Tail logs in real time',
      'exec -it <pod> -- sh  Open shell in a running pod',
      'port-forward          Forward local port to pod port',
      'scale --replicas=N    Scale a deployment',
      'rollout status        Check rollout progress',
      'rollout undo          Roll back a deployment',
      '-n <namespace>        Specify namespace',
      '--all-namespaces      Operate across all namespaces',
      '-o yaml / -o json     Output resource as YAML or JSON',
      'config use-context    Switch between clusters/contexts',
      'top pods              Show CPU/memory usage of pods',
      'cp <pod>:<path> .     Copy files from pod to local',
      'edit <resource>       Open resource in editor for live editing',
    ],
    capabilities: [
      'Deploy and update applications using manifest files',
      'Inspect pod status, events, and describe resource state',
      'Stream and filter container logs across pods',
      'Execute commands and open shells inside running pods',
      'Scale deployments and manage rollout history',
      'Roll back failed deployments to a previous revision',
      'Port-forward for local access to in-cluster services',
      'Manage namespaces, ConfigMaps, Secrets, and RBAC resources',
      'Apply and delete Kubernetes manifests from files or stdin',
      'Switch cluster contexts and manage kubeconfig',
    ],
    useCases: ['Debug a failing pod by tailing its logs and exec-ing in', 'Roll back a bad deployment to the last stable revision', 'Apply a Kubernetes manifest to deploy a new service version'],
  },

  aws: {
    name: 'aws',
    displayName: 'AWS CLI',
    description: 'The AWS CLI is the official command-line interface for managing Amazon Web Services resources across all AWS services.',
    docsUrl: 'https://docs.aws.amazon.com/cli/latest/reference/',
    commonFlags: [
      '--profile <name>      Use a named credentials profile',
      '--region <region>     AWS region override',
      '--output <format>     Output format: json, text, table, yaml',
      '--query <expr>        JMESPath query to filter output',
      '--dry-run             Preview without executing (where supported)',
      '--no-cli-pager        Disable pager for output',
      's3 cp / sync          Copy or sync files to/from S3',
      's3 ls                 List S3 buckets and objects',
      'ec2 describe-*        Describe EC2 instances, VPCs, security groups',
      'ecs update-service    Update ECS service task definition',
      'lambda invoke         Invoke a Lambda function',
      'ssm get-parameter     Retrieve a Parameter Store value',
      'secretsmanager get-secret-value  Retrieve a secret',
      'cloudformation deploy Deploy a CloudFormation stack',
      'iam list-users        List IAM users',
      'logs tail <group>     Tail CloudWatch log group',
      'configure             Set credentials and default region',
      '--endpoint-url        Override endpoint (e.g. LocalStack)',
    ],
    capabilities: [
      'Manage S3 buckets: upload, download, sync, and list objects',
      'Control EC2 instances: start, stop, describe, and connect',
      'Deploy and update Lambda functions and ECS services',
      'Retrieve secrets and parameters from Secrets Manager and SSM',
      'Deploy CloudFormation stacks and check stack events',
      'Tail and filter CloudWatch logs in real time',
      'Manage IAM users, roles, and policies',
      'Query any AWS resource with JMESPath --query filtering',
      'Use named profiles and MFA for multi-account workflows',
      'Automate infrastructure operations in shell scripts and CI/CD',
    ],
    useCases: ['Sync build artifacts to S3 after a CI build', 'Retrieve a secret from Secrets Manager in a deployment script', 'Tail CloudWatch logs for a Lambda function during debugging'],
  },
};

export function getTool(name) {
  const tool = TOOLS[name?.toLowerCase()];
  if (!tool) {
    const valid = Object.keys(TOOLS).join(', ');
    throw new Error(`Unknown tool "${name}". Valid tools: ${valid}`);
  }
  return tool;
}
