export const TOOLS = {
  ffuf: {
    name: 'ffuf',
    displayName: 'ffuf',
    description: 'ffuf (Fuzz Faster U Fool) is a fast web fuzzer written in Go, used for directory/file discovery, parameter fuzzing, and virtual host enumeration.',
    docsUrl: 'https://github.com/ffuf/ffuf',
    commonFlags: [
      '-u <url>          Target URL with FUZZ keyword as placeholder',
      '-w <wordlist>     Wordlist file path (use - for stdin)',
      '-H <header>       Custom header (repeatable: -H "Cookie: x=1")',
      '-mc <codes>       Match HTTP status codes (default: 200,204,301,302,307,401,403)',
      '-fc <codes>       Filter HTTP status codes',
      '-ms <size>        Match response size',
      '-fs <size>        Filter response size',
      '-fw <words>       Filter by word count',
      '-fl <lines>       Filter by line count',
      '-t <threads>      Concurrent threads (default: 40)',
      '-o <file>         Output file path',
      '-of <format>      Output format: json, ejson, html, md, csv, ecsv',
      '-c                Colorize output',
      '-v                Verbose output',
      '-r                Follow redirects',
      '-p <delay>        Delay between requests (e.g. 0.1 or 0.1-2.0)',
      '-recursion        Enable recursive fuzzing',
      '-d <body>         POST data with FUZZ keyword',
      '-X <method>       HTTP method (default: GET)',
      '-b <cookies>      Cookie header value',
    ],
    capabilities: [
      'Directory and file discovery via wordlist fuzzing',
      'Virtual host (vhost) enumeration by fuzzing Host header',
      'Parameter name and value fuzzing for API endpoints',
      'Subdomain discovery using DNS-based fuzzing',
      'POST body fuzzing for form inputs and JSON APIs',
      'Multi-position fuzzing using multiple FUZZ keywords (W1, W2...)',
      'Response filtering by status code, size, word count, or line count',
      'Output results in JSON, CSV, HTML, or Markdown formats',
      'Recursive directory fuzzing with depth control',
      'Request rate limiting to avoid detection/blocking',
      'Cluster bomb and pitchfork attack modes for multi-parameter fuzzing',
    ],
    useCases: ['Find hidden admin panels', 'Enumerate API endpoints', 'Discover backup files with common extensions', 'Fuzz parameter values for injection testing'],
  },

  nmap: {
    name: 'nmap',
    displayName: 'Nmap',
    description: 'Nmap (Network Mapper) is an open-source tool for network discovery, port scanning, service detection, and security auditing.',
    docsUrl: 'https://nmap.org/book/man.html',
    commonFlags: [
      '-p <ports>        Port ranges (e.g. 80,443 or 1-1000 or -p-)',
      '-sV               Service version detection',
      '-sS               SYN (stealth) scan (requires root)',
      '-sU               UDP scan',
      '-sC               Run default NSE scripts',
      '-A                Aggressive scan: OS, version, scripts, traceroute',
      '-O                OS detection (requires root)',
      '-oA <basename>    Output in all formats (normal, XML, grepable)',
      '-oN <file>        Normal output to file',
      '-oX <file>        XML output to file',
      '-oG <file>        Grepable output to file',
      '-T<0-5>           Timing template (0=paranoid, 3=normal, 5=insane)',
      '--script <name>   Run specific NSE scripts',
      '--open            Only show open ports',
      '-v                Verbose output',
      '-n                No DNS resolution',
      '--min-rate <n>    Minimum packet rate',
      '-iL <file>        Input from host list file',
      '--exclude <hosts> Exclude hosts from scan',
    ],
    capabilities: [
      'TCP and UDP port scanning across single hosts or entire subnets',
      'Service and version detection for running processes',
      'Operating system fingerprinting using TCP/IP stack analysis',
      'NSE (Nmap Scripting Engine) for vulnerability detection',
      'Host discovery: ping, ARP, DNS, and SYN probes',
      'Firewall and IDS evasion techniques (fragmentation, decoys)',
      'Traceroute and network topology mapping',
      'Output in XML, JSON-compatible, grepable, and normal formats',
      'Parallel scanning with configurable timing and rate control',
      'SMB, HTTP, SSL/TLS, and SSH service interrogation scripts',
      'Vulnerability scanning with vuln script category',
    ],
    useCases: ['Enumerate open ports on a target during recon', 'Detect service versions for CVE matching', 'Identify live hosts on a subnet', 'Run vuln scripts for quick assessment'],
  },

  gobuster: {
    name: 'gobuster',
    displayName: 'Gobuster',
    description: 'Gobuster is a tool for brute-forcing URIs, DNS subdomains, virtual host names, S3/GCS buckets, and TFTP servers.',
    docsUrl: 'https://github.com/OJ/gobuster',
    commonFlags: [
      'dir                Directory/file brute-force mode',
      'dns                DNS subdomain brute-force mode',
      'vhost              Virtual host brute-force mode',
      '-u <url>           Target URL (dir/vhost mode)',
      '-d <domain>        Target domain (dns mode)',
      '-w <wordlist>      Path to wordlist',
      '-t <threads>       Concurrent threads (default: 10)',
      '-x <extensions>    File extensions to append (e.g. php,html,txt)',
      '-o <file>          Output file path',
      '-s <codes>         Positive status codes (default: 200,204,301,302,307,401,403)',
      '-b <codes>         Negative status codes to blacklist',
      '-l                 Include length of response body',
      '-q                 Quiet mode',
      '-r                 Follow redirects',
      '-k                 Skip TLS certificate verification',
      '-H <header>        Custom headers',
      '-c <cookie>        Cookie to use for requests',
      '--no-error         Suppress error messages',
      '-z                 Show progress',
    ],
    capabilities: [
      'Directory and file brute-forcing with wordlists and extension appending',
      'DNS subdomain enumeration with wildcard detection',
      'Virtual host discovery by brute-forcing Host header',
      'AWS S3 and GCS bucket enumeration',
      'Configurable status code filtering (whitelist and blacklist)',
      'Multi-threaded scanning with progress reporting',
      'Custom header injection for authenticated scanning',
      'Output to file in plaintext format',
      'TLS/SSL certificate verification bypass',
      'Redirect following with depth control',
    ],
    useCases: ['Brute-force directories on a web server', 'Enumerate subdomains of a domain', 'Find virtual hosts behind an IP', 'Discover PHP/ASP/HTML files in a directory'],
  },

  sqlmap: {
    name: 'sqlmap',
    displayName: 'sqlmap',
    description: 'sqlmap is an open-source penetration testing tool that automates the detection and exploitation of SQL injection vulnerabilities.',
    docsUrl: 'https://sqlmap.org',
    commonFlags: [
      '-u <url>           Target URL',
      '-p <param>         Testable parameter',
      '--data <data>      POST data string',
      '--cookie <cookie>  HTTP Cookie header value',
      '--headers <hdrs>   Extra headers (newline-separated)',
      '--dbs              Enumerate databases',
      '--tables           Enumerate tables (-D for specific DB)',
      '--columns          Enumerate columns (-T for specific table)',
      '--dump             Dump table contents',
      '--dump-all         Dump all databases',
      '-D <db>            DBMS database to enumerate',
      '-T <table>         DBMS table to enumerate',
      '-C <columns>       Comma-delimited column list',
      '--level <1-5>      Level of tests to perform (default: 1)',
      '--risk <1-3>       Risk of tests to perform (default: 1)',
      '--batch            Never ask for user input, use defaults',
      '--random-agent     Use random HTTP User-Agent',
      '--technique <tech> SQL injection techniques (BEUSTQ)',
      '--dbms <dbms>      Force backend DBMS',
      '--os-shell         Prompt for OS shell (requires stacked queries)',
    ],
    capabilities: [
      'Automatic detection of SQL injection flaws (boolean, time-based, error, union, stacked)',
      'Database fingerprinting (MySQL, PostgreSQL, MSSQL, Oracle, SQLite, etc.)',
      'Enumeration of databases, tables, columns, and row data',
      'Data extraction via UNION-based, error-based, and blind techniques',
      'File system access: read and write files on the server',
      'Operating system command execution via xp_cmdshell or stacked queries',
      'Privilege escalation checks and user account enumeration',
      'Tamper scripts for WAF/IDS evasion',
      'Session token and cookie injection',
      'Bulk scanning using -m flag for multiple targets',
    ],
    useCases: ['Test a login form for SQLi vulnerabilities', 'Dump the users table from a vulnerable app', 'Check for blind SQLi in a search endpoint', 'Enumerate all databases on a target'],
  },

  burpsuite: {
    name: 'burpsuite',
    displayName: 'Burp Suite',
    description: 'Burp Suite is a web application security testing platform with proxy, scanner, intruder, repeater, and collaborator tools. The REST API enables automation.',
    docsUrl: 'https://portswigger.net/burp/documentation/desktop/tools',
    commonFlags: [
      'Proxy        Intercept and modify HTTP/S traffic',
      'Scanner      Automated vulnerability scanning (Pro/Enterprise)',
      'Intruder     Automated parameter fuzzing with payload lists',
      'Repeater     Manual request replay and modification',
      'Sequencer    Token entropy analysis',
      'Decoder      Encode/decode data (Base64, URL, HTML, etc.)',
      'Comparer     Diff two requests or responses',
      'Collaborator Out-of-band vulnerability testing (SSRF, blind XSS)',
      'REST API     /scan, /issues, /target, /proxy endpoints (localhost:1337)',
    ],
    capabilities: [
      'HTTP/S proxy with full request/response interception and modification',
      'Automated web vulnerability scanning for OWASP Top 10',
      'Intruder: cluster bomb, sniper, pitchfork, and battering ram attack modes',
      'Repeater: replay and modify individual requests with diffing',
      'Out-of-band (OAST) detection via Burp Collaborator',
      'REST API for scripted scan initiation, status polling, and issue retrieval',
      'Target scope management and site map generation',
      'Active and passive scanning with configurable issue categories',
      'Session handling rules for cookie and token management',
      'Extension support via BApp Store and custom Java/Python extensions',
    ],
    useCases: ['Intercept and replay authenticated API requests', 'Automate scans via REST API in CI/CD', 'Fuzz form inputs with custom payload lists', 'Test OAuth flows with Repeater'],
  },

  gh: {
    name: 'gh',
    displayName: 'GitHub CLI (gh)',
    description: 'The GitHub CLI (gh) brings GitHub to the terminal: PRs, issues, repos, gists, actions, and the GitHub API — all from the command line.',
    docsUrl: 'https://cli.github.com/manual',
    commonFlags: [
      'gh pr create       Create a pull request',
      'gh pr list         List pull requests',
      'gh pr view <num>   View a pull request',
      'gh pr merge <num>  Merge a pull request',
      'gh pr checkout     Check out a PR branch locally',
      'gh issue create    Create an issue',
      'gh issue list      List issues with filters',
      'gh issue close     Close an issue',
      'gh issue comment   Add a comment to an issue',
      'gh repo clone      Clone a repository',
      'gh repo create     Create a new repository',
      'gh repo fork       Fork a repository',
      'gh run list        List workflow runs',
      'gh run view        View a workflow run',
      'gh run watch       Watch a workflow run in real time',
      'gh api <endpoint>  Make a raw API call',
      'gh auth login      Authenticate with GitHub',
      'gh gist create     Create a gist',
      'gh release create  Create a release',
    ],
    capabilities: [
      'Full pull request lifecycle: create, view, review, merge, close',
      'Issue management: create, label, assign, close, comment',
      'Repository operations: clone, fork, create, view, delete',
      'GitHub Actions: list runs, view logs, re-run jobs, download artifacts',
      'Release management: create, upload assets, delete',
      'Direct REST and GraphQL API access via gh api',
      'Gist creation and management',
      'Authentication and credential management',
      'Environment and secret management for repos and orgs',
      'Code search, topic, and label management',
    ],
    useCases: ['Create PRs from a feature branch in CI', 'Bulk-close stale issues via scripting', 'Trigger and monitor GitHub Actions workflows', 'Manage repo secrets from the terminal'],
  },

  vercel: {
    name: 'vercel',
    displayName: 'Vercel CLI',
    description: 'The Vercel CLI deploys and manages projects on Vercel: deployments, env vars, domains, logs, and local dev.',
    docsUrl: 'https://vercel.com/docs/cli',
    commonFlags: [
      'vercel            Deploy current directory (preview)',
      'vercel --prod     Deploy to production',
      'vercel dev        Start local dev server with edge functions',
      'vercel env ls     List env variables',
      'vercel env add    Add an env variable interactively',
      'vercel env rm     Remove an env variable',
      'vercel env pull   Pull env vars to local .env file',
      'vercel domains ls List domains for a project',
      'vercel domains add Add a domain',
      'vercel logs       Stream deployment logs',
      'vercel inspect    Inspect a deployment',
      'vercel link       Link local directory to a Vercel project',
      'vercel list       List deployments',
      'vercel promote    Promote a deployment to production',
      'vercel rollback   Roll back to a previous deployment',
      'vercel pull       Pull project settings from Vercel',
      'vercel build      Build locally using Vercel build pipeline',
      '--token <token>   Pass Vercel token for CI environments',
    ],
    capabilities: [
      'Deploy projects to preview and production environments',
      'Local development server with Vercel edge function simulation',
      'Environment variable management across development, preview, production',
      'Domain registration, assignment, and DNS management',
      'Real-time log streaming for deployments and functions',
      'Deployment inspection: URL, build logs, function details',
      'Production promotion and rollback',
      'Project linking and configuration management',
      'Build cache management and forced rebuilds',
      'Team and project switching via --scope flag',
    ],
    useCases: ['Deploy a Next.js app to production', 'Sync env vars to local .env for dev', 'Inspect a failed deployment for errors', 'Promote a preview to production after QA'],
  },

  stripe: {
    name: 'stripe',
    displayName: 'Stripe CLI',
    description: 'The Stripe CLI lets you build, test, and debug Stripe integrations locally: webhook forwarding, API calls, event triggering, and fixture loading.',
    docsUrl: 'https://stripe.com/docs/stripe-cli',
    commonFlags: [
      'stripe listen          Forward webhooks to localhost',
      'stripe trigger <event> Trigger a test webhook event',
      'stripe login           Authenticate with your Stripe account',
      'stripe logs tail       Tail Stripe API request logs',
      'stripe customers list  List customers',
      'stripe customers retrieve <id>  Retrieve a customer',
      'stripe payment-intents create   Create a payment intent',
      'stripe subscriptions list       List subscriptions',
      'stripe fixtures run <file>      Run a fixtures file',
      'stripe open dashboard           Open the Stripe dashboard',
      '--api-key <key>        Use a specific API key',
      '--stripe-account <id>  Operate on a connected account',
      '--limit <n>            Limit number of results',
      '-d <param>             Additional API parameter (flag-style)',
    ],
    capabilities: [
      'Local webhook forwarding with automatic HTTPS tunnel',
      'Test event triggering for all Stripe event types',
      'API request log tailing in real time',
      'Direct resource management: customers, payment intents, subscriptions',
      'Fixture files for reproducible test data setup and teardown',
      'Multi-account support with --stripe-account flag',
      'Restricted key generation for sandboxed access',
      'Resend recent webhook events for retry testing',
      'Product, price, and coupon management from the terminal',
      'Connected account operations via Stripe Connect',
    ],
    useCases: ['Forward webhooks to local server during development', 'Trigger payment.succeeded to test fulfillment logic', 'Load fixture data for automated test suites', 'Tail API logs when debugging webhook failures'],
  },
};

export function getTool(name) {
  const tool = TOOLS[name?.toLowerCase()];
  if (!tool) {
    const valid = Object.keys(TOOLS).join(', ');
    throw new Error(`Unknown tool "${name}". Valid tools: ${valid}`);
  }
  return tool;
}
